version: '3.8'

services:
  # LightRAG API服务
  lightrag-api:
    image: ${LIGHTRAG_IMAGE_NAME:-hkuds/lightrag:latest}
    container_name: ${LIGHTRAG_CONTAINER_NAME:-lightrag-api}
    restart: unless-stopped
    environment:
      # 基本配置
      - LIGHTRAG_ENABLED=true
      - LIGHTRAG_GRAPH_DB_TYPE=${LIGHTRAG_GRAPH_DB_TYPE:-postgres}
      - LIGHTRAG_DATA_ROOT=/app/data/lightrag
      - LIGHTRAG_BASE_DIR=/app/data/lightrag
      - LIGHTRAG_EMBEDDING_DIM=${LIGHTRAG_EMBEDDING_DIM:-1536}
      - LIGHTRAG_MAX_TOKEN_SIZE=${LIGHTRAG_MAX_TOKEN_SIZE:-8192}
      
      # 数据库连接配置
      - POSTGRES_HOST=${LIGHTRAG_PG_HOST:-postgres} 
      - POSTGRES_PORT=${LIGHTRAG_PG_PORT:-5432}
      - POSTGRES_USER=${LIGHTRAG_PG_USER:-postgres}
      - POSTGRES_PASSWORD=${LIGHTRAG_PG_PASSWORD:-password}
      - POSTGRES_DB=${LIGHTRAG_PG_DB:-lightrag}
      
      # Redis配置
      - REDIS_HOST=${LIGHTRAG_REDIS_HOST:-redis}
      - REDIS_PORT=${LIGHTRAG_REDIS_PORT:-6379}
      - REDIS_PASSWORD=${LIGHTRAG_REDIS_PASSWORD:-}
      
      # LLM模型配置
      - LLM_BINDING=${LIGHTRAG_LLM_BINDING:-openai}
      - LLM_MODEL=${LIGHTRAG_LLM_MODEL:-gpt-4o-mini}
      - LLM_BINDING_HOST=${LIGHTRAG_LLM_API_BASE:-https://api.openai.com/v1}
      - LLM_BINDING_API_KEY=${LIGHTRAG_LLM_API_KEY:-${OPENAI_API_KEY}}
      
      # 嵌入模型配置
      - EMBEDDING_BINDING=${LIGHTRAG_EMBEDDING_BINDING:-openai}
      - EMBEDDING_MODEL=${LIGHTRAG_EMBEDDING_MODEL:-text-embedding-3-small}
      - EMBEDDING_BINDING_HOST=${LIGHTRAG_EMBEDDING_API_BASE:-https://api.openai.com/v1}
      - EMBEDDING_BINDING_API_KEY=${LIGHTRAG_EMBEDDING_API_KEY:-${OPENAI_API_KEY}}
      
      # 工作目录配置
      - LIGHTRAG_WORKDIR_ENABLED=true
      - LIGHTRAG_DEFAULT_WORKDIR=${LIGHTRAG_DEFAULT_WORKDIR:-default}
      
      # LightRAG数据库映射
      - LIGHTRAG_PG_HOST=${LIGHTRAG_PG_HOST:-postgres}
      - LIGHTRAG_PG_PORT=${LIGHTRAG_PG_PORT:-5432}
      - LIGHTRAG_PG_USER=${LIGHTRAG_PG_USER:-postgres}
      - LIGHTRAG_PG_PASSWORD=${LIGHTRAG_PG_PASSWORD:-password}
      - LIGHTRAG_PG_DB=${LIGHTRAG_PG_DB:-lightrag}
      - LIGHTRAG_REDIS_HOST=${LIGHTRAG_REDIS_HOST:-redis}
      - LIGHTRAG_REDIS_PORT=${LIGHTRAG_REDIS_PORT:-6379}
      - LIGHTRAG_REDIS_DB=${LIGHTRAG_REDIS_DB:-1}
      - LIGHTRAG_REDIS_PASSWORD=${LIGHTRAG_REDIS_PASSWORD:-}
      
      # 高级配置
      - LIGHTRAG_USE_SEMANTIC_CHUNKING=${LIGHTRAG_USE_SEMANTIC_CHUNKING:-false}
      - LIGHTRAG_USE_KNOWLEDGE_GRAPH=${LIGHTRAG_USE_KNOWLEDGE_GRAPH:-true}
      - LIGHTRAG_KG_RELATION_THRESHOLD=${LIGHTRAG_KG_RELATION_THRESHOLD:-0.7}
      - LIGHTRAG_MAX_WORKERS=${LIGHTRAG_MAX_WORKERS:-4}
      
    volumes:
      # 数据目录挂载
      - ${LIGHTRAG_BASE_DIR:-./data}:/app/data/lightrag
    ports:
      - "${LIGHTRAG_SERVER_PORT:-9621}:9621"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9621/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

networks:
  app-network:
    external: true
    name: ${LIGHTRAG_DOCKER_NETWORK:-zz-backend-network}
