version: '3.8'

services:
  # PostgreSQL for relational data
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: knowledge_qa
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  # Milvus for vector search
  etcd:
    image: quay.io/coreos/etcd:v3.5.0
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - etcd_data:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    restart: always

  minio:
    image: minio/minio:RELEASE.2023-09-30T07-02-29Z
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: always

  milvus:
    image: milvusdb/milvus:v2.3.2
    depends_on:
      - etcd
      - minio
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - milvus_data:/var/lib/milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    restart: always

  # Redis for caching and Pub/Sub
  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

  # RabbitMQ for message queue
  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always

  # Nacos for service discovery and configuration
  nacos:
    image: nacos/nacos-server:v2.2.3
    environment:
      MODE: standalone
      PREFER_HOST_MODE: hostname
      SPRING_DATASOURCE_PLATFORM: mysql
      MYSQL_SERVICE_HOST: mysql
      MYSQL_SERVICE_DB_NAME: nacos
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_USER: nacos
      MYSQL_SERVICE_PASSWORD: nacos
    ports:
      - "8848:8848"
      - "9848:9848"
    depends_on:
      - mysql
    restart: always

  # MySQL for Nacos
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nacos
      MYSQL_USER: nacos
      MYSQL_PASSWORD: nacos
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

  # Celery Worker - 处理异步任务
  celery-worker:
    build: .
    command: celery -A app.worker worker --loglevel=info --concurrency=4
    volumes:
      - .:/app
      - celery_logs:/app/logs
    depends_on:
      - redis
      - rabbitmq
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/knowledge_qa
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - REDIS_URL=redis://redis:6379/0
      - MILVUS_HOST=milvus
      - MINIO_ENDPOINT=minio:9000
    restart: always
    healthcheck:
      test: ["CMD", "celery", "-A", "app.worker", "inspect", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Celery Beat - 定时任务调度器
  celery-beat:
    build: .
    command: celery -A app.worker beat --loglevel=info
    volumes:
      - .:/app
      - celery_logs:/app/logs
      - celery_beat_data:/app/celerybeat
    depends_on:
      - redis
      - rabbitmq
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/knowledge_qa
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BEAT_SCHEDULE_FILENAME=/app/celerybeat/celerybeat-schedule
    restart: always

  # Flower - Celery监控界面
  flower:
    build: .
    command: celery -A app.worker flower --port=5555 --basic_auth=admin:password
    ports:
      - "5555:5555"
    volumes:
      - .:/app
    depends_on:
      - redis
      - rabbitmq
      - celery-worker
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    restart: always

  # Celery Worker - 专用维护队列
  celery-worker-maintenance:
    build: .
    command: celery -A app.worker worker --loglevel=info --queues=maintenance,monitoring --concurrency=2
    volumes:
      - .:/app
      - celery_logs:/app/logs
    depends_on:
      - redis
      - rabbitmq
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/knowledge_qa
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - REDIS_URL=redis://redis:6379/0
    restart: always

  # Celery Worker - 专用报表队列
  celery-worker-reports:
    build: .
    command: celery -A app.worker worker --loglevel=info --queues=reports,analytics --concurrency=1
    volumes:
      - .:/app
      - celery_logs:/app/logs
    depends_on:
      - redis
      - rabbitmq
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/knowledge_qa
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - REDIS_URL=redis://redis:6379/0
    restart: always

volumes:
  postgres_data:
  etcd_data:
  milvus_data:
  redis_data:
  rabbitmq_data:
  minio_data:
  mysql_data:
  celery_logs:
  celery_beat_data:
