# 本地跨编码器模型
cross_encoder_miniLM:
  type: cross_encoder
  name: "MiniLM-L6 检索重排序模型"
  description: "轻量级英文检索重排序模型"
  model_path: "cross-encoder/ms-marco-MiniLM-L-6-v2"

cross_encoder_multilingual:
  type: cross_encoder
  name: "多语言检索重排序模型"
  description: "支持中英文的多语言检索重排序模型"
  model_path: "cross-encoder/mmarco-mMiniLMv2-L12-H384-v1"

# OpenAI 兼容接口模型
openai_rerank:
  type: api
  name: "OpenAI重排序"
  description: "OpenAI重排序API"
  api_base: "{OPENAI_API_BASE}"
  api_key: "{OPENAI_API_KEY}"
  api_path: "/v1/reranking"
  model_id: "text-embedding-3-large"
  request_format: "openai"
  response_format: "openai"

# 百度文心
baidu_ernie_rerank:
  type: api
  name: "百度文心重排序"
  description: "百度文心一言重排序API"
  api_base: "https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop/rerank"
  api_key: "{BAIDU_API_KEY}"
  access_token_url: "https://aip.baidubce.com/oauth/2.0/token"
  model_id: "ernie-rerank"
  request_format: "baidu"
  response_format: "baidu"
  params:
    secret_key: "{BAIDU_SECRET_KEY}"

# 智谱AI
zhipu_rerank:
  type: api
  name: "智谱重排序"
  description: "智谱重排序API"
  api_base: "https://open.bigmodel.cn/api/paas/v4"
  api_key: "{ZHIPU_API_KEY}"
  api_path: "/rerank"
  model_id: "rerank-8k"
  request_format: "zhipu"
  response_format: "zhipu"

# 讯飞星火
xunfei_rerank:
  type: api
  name: "讯飞重排序"
  description: "讯飞星火重排序API"
  api_base: "https://spark-api.xf-yun.com"
  api_path: "/v2.1/rerank"
  app_id: "{XUNFEI_APP_ID}"
  api_key: "{XUNFEI_API_KEY}"
  secret_key: "{XUNFEI_SECRET_KEY}"
  model_id: "general"
  request_format: "xunfei"
  response_format: "xunfei"

# 默认本地实现
default:
  type: default
  name: "BM25重排序"
  description: "基于BM25的本地重排序实现"
